# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "AtkSharp"; version = "3.24.24.95"; hash = "sha256-NgdWbXToBHhEVbvPrFcwXeit5iaqbBmNPQiC0jPKlnQ="; })
  (fetchNuGet { pname = "CairoSharp"; version = "3.24.24.95"; hash = "sha256-ycdgmQyQ1uSshI/9uMaqn5OBxRF8RADf4Tn/TptE2BU="; })
  (fetchNuGet { pname = "CommandLineParser"; version = "2.9.1"; hash = "sha256-ApU9y1yX60daSjPk3KYDBeJ7XZByKW8hse9NRZGcjeo="; })
  (fetchNuGet { pname = "ELFSharp"; version = "2.17.3"; hash = "sha256-8OaAkLxpa5rIhxbmDSnKLeY06jS7nV66LjBjXxHnOb0="; })
  (fetchNuGet { pname = "Eto.Forms"; version = "2.8.3"; hash = "sha256-bxWYDbgfhc/tFwUVAt1K9bGiixo8o58plQxRnaJzYgM="; })
  (fetchNuGet { pname = "Eto.Platform.Gtk"; version = "2.8.3"; hash = "sha256-U78xU1QwGpCEJTmAYZS5AQJU7d2SqISqZcZ10z0UYis="; })
  (fetchNuGet { pname = "FluentFTP"; version = "49.0.2"; hash = "sha256-NUJeuIOkBxwrnmGYMRXfr55T0utVhWbPi7fj8/HSWZE="; })
  (fetchNuGet { pname = "GdkSharp"; version = "3.24.24.95"; hash = "sha256-NYjADgZG9TUQDIZiSSXDAxj5PyX/B7oKRo9f8Oyb4vI="; })
  (fetchNuGet { pname = "GioSharp"; version = "3.24.24.95"; hash = "sha256-5THx4af5PghPnQxXdnsC+wtVcoslh+0636WkB1FaPYg="; })
  (fetchNuGet { pname = "GLibSharp"; version = "3.24.24.95"; hash = "sha256-1pDRkKoUI9fLJBcTA2DBlpVccJl2GyAdL+VKjsFbttA="; })
  (fetchNuGet { pname = "GtkSharp"; version = "3.24.24.95"; hash = "sha256-sBvk5Ecf2i6c2fYVjMBVoXz0I6IlucOWeE2czZH9QHg="; })
  (fetchNuGet { pname = "Newtonsoft.Json"; version = "13.0.3"; hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc="; })
  (fetchNuGet { pname = "PangoSharp"; version = "3.24.24.95"; hash = "sha256-YhltIz1jisJqR2ZxvbYy0ybi4oGw6qR2SkjF/2aWiBQ="; })
  (fetchNuGet { pname = "SCEToolSharp"; version = "1.1.5"; hash = "sha256-WgOFsoo7mbANLdjTZVZ9ZFoMbU9ekLGIpvgAzFLns9E="; })
  (fetchNuGet { pname = "Sentry"; version = "4.4.0"; hash = "sha256-FImXGJoTmNMxsKGEoRh5mfJ1nc1WiUJdli6pYNJys1w="; })
]
